### PR TITLE
Fix Jupyter (and other library) compatibility

### PR DESCRIPTION
**Pull request by ShayBox**
Hard to explain, but it fixes Jupyter compatibility, and compatibility with any other library that uses asyncio, you can still do the manual disable listed in the readme but this should automatically fix most situations.

### CODE REVIEW

**Comment by ShayBox** [comment]
I would recommend a squash merge if you merge this, I used the web editor so there's a lot of commits

**Comment by ShayBox** [comment]
Forgot `device_manager.py`, now the pr works

**Comment by piekstra** [comment]
I've not had time to investigate this PR in more detail yet. I want to do some testing myself locally with a jupyter environment to verify. I also am still deciding if this change makes sense from a design standpoint. Wrapping an existing library (`asyncio`) with custom code to handle a particular edge case when using a separate platform (jupyter) feels dangerous and prone to causing bugs when updating the `asyncio` dependency. 

The provided workaround in the README should work for any functions in this library. E.g. 
```python3
function_thread = threading.Thread(target=device_manager.any_function_example, args=[some_arg, another_arg])
function_thread.start()
result = function_thread.join()
```

**Comment by ShayBox** [comment]
The problem is this doesn't just effect Jupiter, only one library can use asyncio at one time, so if I'm using this with fastapi or discord.py for example, this one doesn't work.

I'm not sure something this simple really needs asyncio in the first place, but this is the only way I know of to fix this problem.

**Comment by piekstra** [comment]
closed in favor of https://github.com/piekstra/tplink-cloud-api/pull/53

will cut a release shortly

**Comment by piekstra** [comment]
Compatibility with async libraries is published and available :)

https://github.com/piekstra/tplink-cloud-api/releases/tag/v4.0.0

**Pull request closed without merging**
